version: '3.9'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8001:8000"
    restart: unless-stopped
    # volumes:                  # Раскомментируйте для разработки
    #   - ./backend:/backend